stages:
  - test
  - build
  - docker

# Backend Test Job
backend_test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-21
  cache:
    key: maven-cache
    paths:
      - backend/.m2/repository
    policy: pull-push
  before_script:
    - cd backend
  script:
    - ./mvnw test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/*.xml
  only:
    - main

# Backend Build Job
backend_build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  cache:
    key: maven-cache
    paths:
      - backend/.m2/repository
    policy: pull-push
  before_script:
    - cd backend
    - chmod +x ./mvnw
  script:
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
    expire_in: 1 hour
  dependencies:
    - backend_test
  only:
    - main

# Frontend Build Job
frontend_build:
  stage: build
  image: node:18-alpine
  cache:
    key: npm-cache
    paths:
      - frontend/node_modules/
    policy: pull-push
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 hour
  only:
    - main

# Docker Build and Push Backend
docker_backend:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker build -t rida999/mock-backend:latest ./backend
    - docker push rida999/mock-backend:latest
  dependencies:
    - backend_build
  only:
    - main
  after_script:
    - docker system prune -f

# Docker Build and Push Frontend
docker_frontend:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker build -t rida999/mock-frontend:latest ./frontend
    - docker push rida999/mock-frontend:latest
  dependencies:
    - frontend_build
  only:
    - main
  after_script:
    - docker system prune -f
